Repository Soptrail/korail-iOS, pull requests merged in 2022-11, with the labels that each got.

#3 [Setting] #1 - 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  Korail-iOS/Korail-iOS.xcodeproj/project.pbxproj
  Korail-iOS/Korail-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Korail-iOS/Korail-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Korail-iOS/Korail-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Korail-iOS/Korail-iOS/Global/Extension/.gitkeep
  Korail-iOS/Korail-iOS/Global/Literal/.gitkeep
  Korail-iOS/Korail-iOS/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Korail-iOS/Korail-iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Korail-iOS/Korail-iOS/Global/Resource/Assets.xcassets/Contents.json
  Korail-iOS/Korail-iOS/Global/Resource/Base.lproj/LaunchScreen.storyboard
  Korail-iOS/Korail-iOS/Global/Resource/Fonts/.gitkeep
  Korail-iOS/Korail-iOS/Global/Supports/AppDelegate.swift
  Korail-iOS/Korail-iOS/Global/Supports/SceneDelegate.swift
  Korail-iOS/Korail-iOS/Global/UIComponents/.gitkeep
  Korail-iOS/Korail-iOS/Global/Utils/.gitkeep
  Korail-iOS/Korail-iOS/Info.plist
  Korail-iOS/Korail-iOS/Network/APIService/.gitkeep
  Korail-iOS/Korail-iOS/Network/Foundation/.gitkeep
  Korail-iOS/Korail-iOS/Network/Model/.gitkeep
  Korail-iOS/Korail-iOS/Screens/TicketConfirmationScene/.gitkeep
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/InfoFormView/.gitkeep
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/LocationFormView/.gitkeep
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/TrainInquiryView/.gitkeep
  Korail-iOS/Korail-iOS/ViewController.swift
Labels: 세진

#6 [Setting] #5 - Extension 추가
  Korail-iOS/Korail-iOS.xcodeproj/project.pbxproj
  Korail-iOS/Korail-iOS/Global/Extension/UILabel+.swift
  Korail-iOS/Korail-iOS/Global/Extension/UITextField+.swift
  Korail-iOS/Korail-iOS/Global/Extension/UIView+.swift
  Korail-iOS/Korail-iOS/Global/Utils/Adjusted+.swift
  Korail-iOS/Korail-iOS/Global/Utils/ApplyShadow.swift
  Korail-iOS/Korail-iOS/Global/Utils/getClassName.swift
Labels: 세진, Setting

#9 [Feat] #7 - LocationFormVC UI 구현
  Korail-iOS/Korail-iOS.xcodeproj/project.pbxproj
  Korail-iOS/Korail-iOS/Global/Literal/ImageLiterals.swift
  Korail-iOS/Korail-iOS/Global/Resource/Assets.xcassets/ic_change.imageset/Contents.json
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/LocationFormView/LocationFormVC.swift
Labels: 세진, Feat

#12 [Feat] #11 - 승차권 예매 조회 API 연결
  Korail-iOS/Korail-iOS.xcodeproj/project.pbxproj
  Korail-iOS/Korail-iOS/Global/Extension/Encodable+.swift
  Korail-iOS/Korail-iOS/Network/Dto/.gitkeep
  Korail-iOS/Korail-iOS/Network/Dto/TrailLocationResponseDto.swift
  Korail-iOS/Korail-iOS/Network/Foundation/APIConstants.swift
  Korail-iOS/Korail-iOS/Network/Foundation/NetworkLoggerPlugin.swift
  Korail-iOS/Korail-iOS/Network/Router/.gitkeep
  Korail-iOS/Korail-iOS/Network/Router/TrailRouter.swift
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/LocationFormView/LocationFormVC.swift
Labels: 세진, Feat

#15 Feature/#14 캘린더뷰 구현
  Korail-iOS/Korail-iOS.xcodeproj/project.pbxproj
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/InfoFormView/InfoFormVC.swift
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/InfoFormView/InfoModel.swift
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/InfoFormView/PeopleInfoTableViewCell.swift
  Korail-iOS/Korail-iOS/Screens/TicketReservationScene/LocationFormView/LocationFormVC.swift
Labels: 누리, Feat
